### ISSUE TITLE
Installation fails with download error

### ISSUE THREAD

**Issue by AuthenticPumpkin** [hyphone/sn-theme-vscode#4]
In the Standard Notes web app, if I do "Import Extension" and then paste in the follow url:
https://laux.wtf/sn/sn-vscode-theme/ext.json

this error text is presented:
"Error downloading package details. Please check the Extension Link and try again."

I have been able to install scratch editor just now, so my setup is working ok. For reference - it turns out that scratch editor had a similar issue a few weeks ago and were able to resolve it - dylanonelson/sn-scratch-editor#27

**Comment by hyphone** [comment]
Interesting - thank you very much for letting me know!

I have never tried it with the web app, just the client application.

I fixed the CORS errors and was now able to successfully import it within the web app.

Can you confirm this on your end?

**Comment by AuthenticPumpkin** [comment]
Thank you! It's fixed.

Thank you for all your work on this!
