### ISSUE TITLE
VS Code Theme whitescreens IOS app

### ISSUE THREAD

**Issue by newbery** [hyphone/sn-theme-vscode#6]
Moved from https://github.com/standardnotes/forum/issues/2224

**Describe the bug**
The VS Code Theme appears to result in iphone white screen of death

**To Reproduce**
1. In desktop app, switch to VS Code Theme
2. In ios app, attempt to create a new note. A few seconds in (maybe the delay before the theme switch is synced), and then the screen goes completely white.
3. Go back to desktop app, and switch back to Default appearance. Wait a few seconds and then the display for the ios app becomes visible again.

**Expected behavior**
Obviously, changing theme in the desktop app should not kill the ios app.

**Desktop:**
 - OSX 12.6
 - Standard Notes 3.23.238
 
**Smartphone:**
 - iPhone SE, ios 15.6.1
 - Standard Notes 3.43.5

**Comment by marcolaux** [comment]
I'm sorry but I can't reproduce this as I don't have access to an iOS device.
You don't have issues with other 3rd party themes?

**Comment by marcolaux** [comment]
I've seem some old metadata in the linked issue.
Do you still experience this with this URL: https://laux.wtf/sn/sn-vscode-theme/ext.json

SN in the past had issues with caching. It often was frustrating for me to debug and get the newest version on a mobile device as it never downloaded the newest version.
Is it possible to delete the caches in the iOS app?

**Comment by marcolaux** [comment]
oh and please try the new mobile experience in the preferences. This at least seem to fetch the sources more reliably.
